language: node_js
sudo: false
node_js:
  - 7

cache:
  directories:
    - ~/.npm
    - ~/.yarn-cache

git:
  depth: 10

branches:
  only:
    - master

before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm i -g npm@^5

install:
  - npm i
